# This file is autogenerated by the flake.nix file, do not edit
source "https://rubygems.org"

# Gems dependencies to be installed
gem "webrick", "~> 1.8"
gem "github-pages", "~> 232", group: :jekyll_plugins

# Github Pages plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-theme-cayman", "~> 0.2.0"
end

